package br.com.tarlis.mov3lets.run;


import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;

import br.com.tarlis.mov3lets.method.Mov3lets;
import br.com.tarlis.mov3lets.utils.ProgressBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * The Class MASTERMoveletsGUI.
 *
 * @author tarlis
 */
public class MASTERMoveletsGUI extends javax.swing.JFrame {

    /**
     * Creates new form MASTERMoveletsGUI.
     */
    public MASTERMoveletsGUI() {
        initComponents();
        Mov3lets.progressBar = new ProgressBar() {
        	
        	public void setPrefix(String prefix) {
        		super.setPrefix(prefix);
        		println(prefix);
        	}
        	
            public synchronized void update(long done, long total, String message) {
                message = (message != null? ">> "+message + "." : "");
        		println(message);
                
                bar.setMaximum((int) total);
                bar.setValue((int) done);
            }
        	
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbV1 = new javax.swing.JRadioButton();
        rbV2 = new javax.swing.JRadioButton();
        rbSuper = new javax.swing.JRadioButton();
        rbHiper = new javax.swing.JRadioButton();
        ckLog = new javax.swing.JCheckBox();
        ckIndex = new javax.swing.JCheckBox();
        ckInterning = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txThreads = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txms = new javax.swing.JTextField();
        lbMs = new javax.swing.JLabel();
        txMs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txEd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txSamples = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txSampleSize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txQ = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txOut = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txMedium = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnRun = new javax.swing.JButton();
        bar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txOutput = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txFileds = new javax.swing.JTextField();
        btnFileDs = new javax.swing.JButton();
        txFileRes = new javax.swing.JTextField();
        btnFileRes = new javax.swing.JButton();
        txDescriptor = new javax.swing.JTextField();
        btnFileDescriptor = new javax.swing.JButton();
        btnQueue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASTER Movelets");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Version:"));

        buttonGroup1.add(rbV1);
        rbV1.setText("1.0");

        buttonGroup1.add(rbV2);
        rbV2.setText("2.0");

        buttonGroup1.add(rbSuper);
        rbSuper.setText("Super");

        buttonGroup1.add(rbHiper);
        rbHiper.setSelected(true);
        rbHiper.setText("Hiper");

        ckLog.setSelected(true);
        ckLog.setText("Log");
        ckLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLogActionPerformed(evt);
            }
        });

        ckIndex.setText("Indexed");
        ckIndex.setEnabled(false);

        ckInterning.setSelected(true);
        ckInterning.setText("Interning");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbV2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSuper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbHiper))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckInterning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckIndex))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbV1)
                    .addComponent(rbV2)
                    .addComponent(rbSuper)
                    .addComponent(rbHiper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckLog)
                    .addComponent(ckIndex)
                    .addComponent(ckInterning))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Options:"));

        jLabel2.setText("Allowed Threads:");

        txThreads.setText("1");
        txThreads.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Min. Size:");

        txms.setText("1");
        txms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbMs.setText("Max. Size:");
        lbMs.setEnabled(false);

        txMs.setEnabled(false);
        txMs.setText("-3");
        txMs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Max. # of Dimensions:");

        txEd.setText("-1");
        txEd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("Samples:");

        txSamples.setText("1");
        txSamples.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Samples Size:");

        txSampleSize.setText("0.5");
        txSampleSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Quality Measure:");

        txQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LSP - Left Side Pure" }));

        jLabel9.setText("Output:");

        txOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "numeric", "normalized", "discrete" }));

        jLabel10.setText("Medium:");

        txMedium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "minmax", "sd", "interquartil" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txms, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbMs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txMs, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txEd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txSamples)
                            .addComponent(txSampleSize, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txOut, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txQ, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMedium, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txSampleSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lbMs)
                            .addComponent(txMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        txOutput.setColumns(20);
        txOutput.setRows(5);
        txOutput.setEnabled(true);
        jScrollPane1.setViewportView(txOutput);

        jLabel11.setText("Datasets Dir.:");

        jLabel12.setText("Results Dir.:");

        jLabel13.setText("Descriptor:");

        btnFileDs.setText("Choose");
        btnFileDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileDsActionPerformed(evt);
            }
        });

        btnFileRes.setText("Choose");
        btnFileRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileResActionPerformed(evt);
            }
        });

        btnFileDescriptor.setText("Choose");
        btnFileDescriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileDescriptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFileds)
                            .addComponent(txFileRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFileDs)
                            .addComponent(btnFileRes)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txDescriptor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFileDescriptor)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFileds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileDs)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txFileRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txDescriptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFileDescriptor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnQueue.setText("Queue");
        btnQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRun))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(407, 407, 407))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRun)
                                .addComponent(btnQueue))
                            .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    /**
     * Btn file ds action performed.
     *
     * @param evt the evt
     */
    private void btnFileDsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        JFileChooser j = new JFileChooser(); 
        j.setCurrentDirectory(new java.io.File("."));
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // Open the save dialog 
        if (j.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txFileds.setText(j.getSelectedFile().getAbsolutePath());
        }
    }                                         

    /**
     * Btn file res action performed.
     *
     * @param evt the evt
     */
    private void btnFileResActionPerformed(java.awt.event.ActionEvent evt) {                                           
        JFileChooser j = new JFileChooser(); 
        j.setCurrentDirectory(new java.io.File("."));
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // Open the save dialog 
        if (j.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txFileRes.setText(j.getSelectedFile().getAbsolutePath());
        }
    }                                          

    /**
     * Btn file descriptor action performed.
     *
     * @param evt the evt
     */
    private void btnFileDescriptorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        JFileChooser j = new JFileChooser(); 
        j.setCurrentDirectory(new java.io.File(
        		txFileds.getText() != null && !txFileds.getText().trim().equals("")?
        				txFileds.getText() : "."));
        j.setFileSelectionMode(JFileChooser.FILES_ONLY);
        // Open the save dialog 
        if (j.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txDescriptor.setText(j.getSelectedFile().getAbsolutePath());
        }
    }                                                 

    /**
     * Ck log action performed.
     *
     * @param evt the evt
     */
    private void ckLogActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (ckLog.isSelected()) {
            lbMs.setEnabled(false);
            txMs.setEnabled(false);
        } else  {
            lbMs.setEnabled(true);
            txMs.setEnabled(true);
        }
    }                                     

    /**
     * Btn run action performed.
     *
     * @param evt the evt
     */
    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (queue.isEmpty()) {
        	queue.add(prepareRun());
        }
        
        for (List<String> args : queue) {
        	println("");
    		println("Running:");
        	printCommand(args);
    		println("----------------------------------------------------------------");
        	Mov3letsRun.main((String[]) args.toArray(new String[0])); 
    		println("----------------------------------------------------------------");
		}
        
        queue.clear();
    }                                      

    /** The queue. */
    private List<List<String>> queue = new ArrayList<List<String>>();
    
    /**
     * Btn queue action performed.
     *
     * @param evt the evt
     */
    private void btnQueueActionPerformed(java.awt.event.ActionEvent evt) {                                         
        queue.add(prepareRun());
    }      
    
    /**
     * Prepare run.
     *
     * @return the list
     */
    private List<String> prepareRun() {
    	List<String> params = new ArrayList<String>();

		params.add("-curpath"); 				params.add("\'" + txFileds.getText() + "\'");
		params.add("-respath"); 				params.add("\'" + txFileRes.getText() + "\'");
		params.add("-descfile"); 				params.add("\'" + txDescriptor.getText() + "\'");
		params.add("-nt"); 						params.add(txThreads.getText());
		params.add("-ms"); 						params.add(txms.getText());
		params.add("-Ms"); 						params.add(txMs.getText()); // unlimited maxSize
		params.add("-q"); 						params.add(txQ.getSelectedItem().toString().split(" ")[0]); // LSP | PROP
		params.add("-mnf"); 					params.add(txEd.getText().toString());
		params.add("-samples"); 				params.add(txSamples.getText());		
		params.add("-sampleSize"); 				params.add(txSampleSize.getText());			
		params.add("-medium"); 					params.add(txMedium.getSelectedItem().toString()); // Other values minmax); 		params.add( sd); 		params.add( interquartil
		params.add("-output"); 					params.add(txOut.getSelectedItem().toString()); // Other values numeric discretized
		params.add("-interning"); 				params.add(ckInterning.isSelected() + "");
		params.add("-verbose"); 					params.add("true");
		
		if (rbV1.isSelected()) {
			params.add("-version"); 		params.add("1.0");
		} else if (rbV2.isSelected()) {
			params.add("-version"); 		params.add("2.0");
    	} else if (rbSuper.isSelected()) {
			params.add("-version"); 		params.add("super");
		} else if (rbHiper.isSelected()) {
			params.add("-version"); 		params.add("hiper");
		}

		println("Added to Run:");
		printCommand(params);
				
		return params;
    }

    /**
     * Prints the command.
     *
     * @param args the args
     */
    private void printCommand(List<String> args) {
		println("java -jar MASTERMovelets.jar " + String.join(" ", args));
		println("-------------------------------------------------------------------------------------------------------------------------------");
	}

	/**
	 * Println.
	 *
	 * @param s the s
	 */
	private void println(String s) {
		txOutput.append(s + "\n");
	}

	/**
	 * The main method.
	 *
	 * @param args the command line arguments
	 */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MASTERMoveletsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MASTERMoveletsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MASTERMoveletsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MASTERMoveletsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MASTERMoveletsGUI().setVisible(true);
            }
        });
    }

    /** The bar. */
    // Variables declaration - do not modify                     
    private javax.swing.JProgressBar bar;
    
    /** The btn file descriptor. */
    private javax.swing.JButton btnFileDescriptor;
    
    /** The btn file ds. */
    private javax.swing.JButton btnFileDs;
    
    /** The btn file res. */
    private javax.swing.JButton btnFileRes;
    
    /** The btn queue. */
    private javax.swing.JButton btnQueue;
    
    /** The btn run. */
    private javax.swing.JButton btnRun;
    
    /** The button group 1. */
    private javax.swing.ButtonGroup buttonGroup1;
    
    /** The ck index. */
    private javax.swing.JCheckBox ckIndex;
    
    /** The ck interning. */
    private javax.swing.JCheckBox ckInterning;
    
    /** The ck log. */
    private javax.swing.JCheckBox ckLog;
    
    /** The j label 1. */
    private javax.swing.JLabel jLabel1;
    
    /** The j label 10. */
    private javax.swing.JLabel jLabel10;
    
    /** The j label 11. */
    private javax.swing.JLabel jLabel11;
    
    /** The j label 12. */
    private javax.swing.JLabel jLabel12;
    
    /** The j label 13. */
    private javax.swing.JLabel jLabel13;
    
    /** The j label 2. */
    private javax.swing.JLabel jLabel2;
    
    /** The j label 3. */
    private javax.swing.JLabel jLabel3;
    
    /** The j label 5. */
    private javax.swing.JLabel jLabel5;
    
    /** The j label 6. */
    private javax.swing.JLabel jLabel6;
    
    /** The j label 7. */
    private javax.swing.JLabel jLabel7;
    
    /** The j label 8. */
    private javax.swing.JLabel jLabel8;
    
    /** The j label 9. */
    private javax.swing.JLabel jLabel9;
    
    /** The j panel 1. */
    private javax.swing.JPanel jPanel1;
    
    /** The j panel 2. */
    private javax.swing.JPanel jPanel2;
    
    /** The j panel 3. */
    private javax.swing.JPanel jPanel3;
    
    /** The j panel 4. */
    private javax.swing.JPanel jPanel4;
    
    /** The j scroll pane 1. */
    private javax.swing.JScrollPane jScrollPane1;
    
    /** The lb ms. */
    private javax.swing.JLabel lbMs;
    
    /** The rb hiper. */
    private javax.swing.JRadioButton rbHiper;
    
    /** The rb super. */
    private javax.swing.JRadioButton rbSuper;
    
    /** The rb V 1. */
    private javax.swing.JRadioButton rbV1;
    
    /** The rb V 2. */
    private javax.swing.JRadioButton rbV2;
    
    /** The tx descriptor. */
    private javax.swing.JTextField txDescriptor;
    
    /** The tx ed. */
    private javax.swing.JTextField txEd;
    
    /** The tx file res. */
    private javax.swing.JTextField txFileRes;
    
    /** The tx fileds. */
    private javax.swing.JTextField txFileds;
    
    /** The tx medium. */
    private javax.swing.JComboBox<String> txMedium;
    
    /** The tx ms. */
    private javax.swing.JTextField txMs;
    
    /** The tx out. */
    private javax.swing.JComboBox<String> txOut;
    
    /** The tx output. */
    private javax.swing.JTextArea txOutput;
    
    /** The tx Q. */
    private javax.swing.JComboBox<String> txQ;
    
    /** The tx sample size. */
    private javax.swing.JTextField txSampleSize;
    
    /** The tx samples. */
    private javax.swing.JTextField txSamples;
    
    /** The tx threads. */
    private javax.swing.JTextField txThreads;
    
    /** The txms. */
    private javax.swing.JTextField txms;
    // End of variables declaration                   
}